### ISSUE TITLE
Q about analogPin

### ISSUE THREAD

**Issue by ChengRui24** [Manghao/LM35#2]
Thanks for providing this useful package!
but I have a little question about the analogPin.
I saw other coder set A0 with OUTPUT, before analogRead(A0).[https://github.com/ggzucco/LM35/blob/master/LM35.cpp](url)
For what I know, this A0 is receive the data from lM35, it should be INPUT mode.
And the page about AnalogInputPins on arduino.cc is writting:

> The analogRead command will not work correctly if a pin has been previously set to an output, so if this is the case, set it back to an input before using analogRead.   

I am new for learning Andruino, so I don't know a lof about this stuff, i can't figure out why, and I can't search out any answer.

thanks again

**Comment by wilmouths** [comment]
By default the analog pins are inputs it seems to me
